### ISSUE TITLE
'module' object has no attribute 'NSIG'

### ISSUE THREAD

**Issue by avelkoski** [locustio/locust#518]
Works on Python 2.7.12 :: Anaconda 4.2.0 (64-bit). However, for me, not on Python 2.7.11 and 2.7.13 :: Anaconda 2.5.0 (64-bit), as well as some Python 2.6.x. Curious if others have seen this.   

data@data:~$ locust -f load_test.py --host=https://somewebsite.com
[2017-01-13 17:08:08,683] data/INFO/locust.main: Starting web monitor at *:8089
[2017-01-13 17:08:08,684] data/ERROR/stderr: Traceback (most recent call last):
[2017-01-13 17:08:08,684] data/ERROR/stderr: File "/anaconda/bin/locust", line 11, in <module>
[2017-01-13 17:08:08,684] data/ERROR/stderr: 
[2017-01-13 17:08:08,684] data/ERROR/stderr: sys.exit(main())
[2017-01-13 17:08:08,684] data/ERROR/stderr: File "/anaconda/lib/python2.7/site-packages/locust/main.py", line 437, in main
[2017-01-13 17:08:08,685] data/ERROR/stderr: 
[2017-01-13 17:08:08,685] data/ERROR/stderr: gevent.signal(signal.SIGTERM, sig_term_handler)
[2017-01-13 17:08:08,685] data/ERROR/stderr: File "/anaconda/lib/python2.7/site-packages/gevent/__init__.py", line 101, in __new__
[2017-01-13 17:08:08,685] data/ERROR/stderr: 
[2017-01-13 17:08:08,685] data/ERROR/stderr: return _signal_class(*args, **kwargs)
[2017-01-13 17:08:08,686] data/ERROR/stderr: File "/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 265, in __init__
[2017-01-13 17:08:08,686] data/ERROR/stderr: 
[2017-01-13 17:08:08,686] data/ERROR/stderr: self.watcher = self.hub.loop.signal(signalnum, ref=False)
[2017-01-13 17:08:08,686] data/ERROR/stderr: File "gevent/core.pyx", line 478, in gevent.core.loop.signal (gevent/gevent.core.c:8689)
[2017-01-13 17:08:08,686] data/ERROR/stderr: File "gevent/core.pyx", line 1136, in gevent.core.signal.__init__ (gevent/gevent.core.c:19627)
[2017-01-13 17:08:08,687] data/ERROR/stderr: AttributeError
[2017-01-13 17:08:08,687] data/ERROR/stderr: :
[2017-01-13 17:08:08,687] data/ERROR/stderr: 'module' object has no attribute 'NSIG'
[2017-01-13 17:08:08,687] data/ERROR/stderr:

**Comment by DonerKebab** [comment]
i have the same issue.

**Comment by iainlbc** [comment]
coworker ran into this as well

module' object has no attribute 'NSIG' error when using Python 2.7.12 :: Anaconda 2.2.0 (x86_64) - OSX

works fine for me on ubuntu using Python 2.7.12

**Comment by daiguadaidai** [comment]
initial version is: gevent-1.1.0
I uninstall gevent

```
pip uninstall gevent
```

install `gevent` version: `gevent-1.0.0`, this opration waiting some time

```
pip install  -i https://pypi.tuna.tsinghua.edu.cn/simple gevent==1.0.0
```
upgrade `gevent` to `gevent-1.1.0`, this opration fast

```
pip install --upgrade  -i https://pypi.tuna.tsinghua.edu.cn/simple gevent==1.1.0
```

upgrade `gevent` to `gevent-1.2.2`, this opration waiting some time

```
pip install --upgrade  -i https://pypi.tuna.tsinghua.edu.cn/simple gevent==1.2.2
```
