### ISSUE TITLE
"IndexError: Cannot choose from an empty sequence" between tasks

### ISSUE THREAD

**Issue by dms-cat** [locustio/locust#954]
### Description of issue

Spurious error messages during execution.

### Environment settings

- OS: [Official ubuntu:18.04 Docker container](https://hub.docker.com/_/ubuntu/)
- Python version: 3.6.7
- Locust version: 0.9.0

### Steps to reproduce

I've registered all my tasks by looping through the OpenAPI JSON for the API like this:

```
class APIRequest(TaskSet):
    def setup(self) -> None:
        for api_path, properties in self.client.get('/api/doc/?format=openapi').json()['paths'].items():
            [exclude some API paths]
            self.schedule_task(self.api_task, args=[api_path])

    def api_task(self, path: str) -> None:
        response = self.client.get("/api{}?limit=1000".format(path))
        assert response.status_code == HTTPStatus.OK, response.content.decode()


class ApiRequests(HttpLocust):
    task_set = APIRequest
    min_wait = 200
    max_wait = 1000
    host = 'https://{}'.format(os.environ['WEB_HOSTNAME'])


if __name__ == '__main__':
    locust = ApiRequests()
    locust.run()
```

I then run Locust: `locust --csv=output/ --locustfile=api.py --no-web --run-time=5m`

### Expected behavior

Locust should run for five minutes and return successfully, reporting progress as it runs.

### Actual behavior

**Even if the run is successful,** Locust will frequently print one, two or three error messages such as the below between each time it prints the summary table:

```
[2019-02-04 00:19:23,150] 2e0a2ecc40ea/ERROR/stderr: Traceback (most recent call last):
  File "/src/app/.venv/lib/python3.6/site-packages/locust/core.py", line 358, in run
    self.schedule_task(self.get_next_task())
  File "/src/app/.venv/lib/python3.6/site-packages/locust/core.py", line 419, in get_next_task
    return random.choice(self.tasks)
  File "/src/app/.venv/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

**Comment by cyberw** [comment]
Looks really strange. Have you tried the latest locust release?

**Comment by cyberw** [comment]
Wait, you havent decorated the task method with `@task`, I think that may be your problem!

**Comment by dms-cat** [comment]
Decorating `api_task` *and* upgrading fixed this issue.

**Comment by dms-cat** [comment]
After upgrading locustio to 0.12.2 and decorating `api_task` with `@task` I now get this error repeatedly after running for a bit:

```text
[2019-10-29 23:33:54,875] 96e674dbf47b/ERROR/stderr: Traceback (most recent call last):
  File "/src/app/.venv/lib/python3.6/site-packages/locust/core.py", line 374, in run
    self.execute_next_task()
  File "/src/app/.venv/lib/python3.6/site-packages/locust/core.py", line 400, in execute_next_task
    self.execute_task(task["callable"], *task["args"], **task["kwargs"])
  File "/src/app/.venv/lib/python3.6/site-packages/locust/core.py", line 412, in execute_task
    task(self, *args, **kwargs)
TypeError: api_task() missing 1 required positional argument: 'path'
```

**Comment by cyberw** [comment]
Tasks dont take parameters, you have added a ”path” argument to your method.

**Comment by cyberw** [comment]
Oh I see what you are trying to do now. remove the call to schedule_tasks. I dont think you are meant to call it yourself. Instead, just populate a list of paths in setup and pick from that list inside your task.

**Comment by meralaz** [comment]
I have been seeing the error:
`TypeError: api_task() missing 1 required positional argument: 'path'` and started searching for explanation and I made it here.
Following the above suggestion, How do you transfer the list to the task method?

```
class LoadTestBehaviour(TaskSet):

    def on_start(self):
        """ on_start is called when a Locust start before any task is scheduled """
        pass

    def on_stop(self):
        """ on_stop is called when the TaskSet is stopping """
        pass

    def setup(self):
        data = self.getJSON()
        #host = requests.get('swagger.json').json()['host']
        #for apiPath in requests.get('swagger.json').json()['paths'].keys():
        self.apis = []
        for apiPath in data['paths'].keys():
            api = "{}{}".format(data['host'], apiPath)
            self.apis.append(api)
            #self.schedule_task(self.APITask, args=[api])

    @task
    def APITask(self):
        response = self.client.get(self.apis[0])
        assert response.status_code == HTTPStatus.OK, response.content.decode()

```

I tried to pick the first item from the list but got the following error:
`AttributeError: 'LoadTestBehaviour' object has no attribute 'apis'`

**Comment by cyberw** [comment]
Setup is run only once (and thus should never have been made an object method, that is a design mistake), so only the first TaskSet instance will have self.apis value.

If you set a class variable (LoadTestBehaviour.apis instead of self.apis), it should work.
